name: file_picker_patch
description: A patch over the file_picker plugin which is a package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
homepage: https://github.com/saurabhdtu/file_picker_patch
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
    
  flutter_plugin_android_lifecycle: ^2.0.0
  plugin_platform_interface: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"
  
dev_dependencies:
#  test: any
#  flutter_driver:
#    sdk: flutter
  flutter_test:
    sdk: flutter
    
flutter:
  plugin:
    platforms:
      android:
        package: com.mr.flutter.plugin.filepicker_patch
        pluginClass: FilePickerPlugin
      ios:
        pluginClass: FilePickerPlugin
      web:
        pluginClass: FilePickerWeb
        fileName: src/file_picker_web.dart
